### ISSUE TITLE
Deploy using serverless is failing

### ISSUE THREAD

**Issue by markatom** [atlassian/localstack#101] opened 2017-05-10 14:09 UTC
Hi, I would like to thank you for an awesome work on localstack. I have been trying deployment of my lambda code to localstack using [serverless](https://serverless.com/) but cloudformation service is failing. I have build of current master.

I ran localstack with debug output `DEBUG=1 make infra` to get more details about the error:

```
. .venv/bin/activate; PYTHONPATH=. exec localstack/mock/infra.py
Starting local dev environment. CTRL-C to quit.
Starting local Elasticsearch (port 4571)...
Starting mock ES service (port 4578)...
Starting mock S3 (port 4572)...
Starting mock SNS (port 4575)...
Starting mock SQS (port 4576)...
Starting mock API Gateway (port 4567)...
Starting mock DynamoDB (port 4569)...
Starting mock DynamoDB Streams service (port 4570)...
Starting mock Firehose service (port 4573)...
Starting mock Lambda service (port 4574)...
Starting mock Kinesis (port 4568)...
Starting mock Redshift (port 4577)...
Starting mock Route53 (port 4580)...
Starting mock SES (port 4579)...
Starting mock CloudFormation (port 4581)...
Listening at http://:::4584
Listening at http://:::4583
* Running on http://0.0.0.0:4586/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4585/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4588/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4579/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4576/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4580/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4577/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4582/ (Press CTRL+C to quit)
127.0.0.1 - - [10/May/2017 15:59:18] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [10/May/2017 15:59:21] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [10/May/2017 15:59:24] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [10/May/2017 15:59:28] "GET / HTTP/1.1" 200 -
[2017-05-10T15:59:28,053][INFO ][o.e.n.Node               ] [] initializing ...
[2017-05-10T15:59:28,181][INFO ][o.e.e.NodeEnvironment    ] [SZjO892] using [1] data paths, mounts [[/ (/dev/disk1)]], net usable_space [265.2gb], net total_space [464.6gb], spins? [unknown], types [hfs]
[2017-05-10T15:59:28,181][INFO ][o.e.e.NodeEnvironment    ] [SZjO892] heap size [483.3mb], compressed ordinary object pointers [true]
[2017-05-10T15:59:28,185][INFO ][o.e.n.Node               ] node name [SZjO892] derived from node ID [SZjO8922TK-StMJpIV_jqg]; set [node.name] to override
[2017-05-10T15:59:28,185][INFO ][o.e.n.Node               ] version[5.3.0], pid[32138], build[3adb13b/2017-03-23T03:31:50.652Z], OS[Mac OS X/10.12.4/x86_64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_112/25.112-b16]
[2017-05-10T15:59:29,163][INFO ][o.e.p.PluginsService     ] [SZjO892] loaded module [aggs-matrix-stats]
[2017-05-10T15:59:29,164][INFO ][o.e.p.PluginsService     ] [SZjO892] loaded module [ingest-common]
[2017-05-10T15:59:29,164][INFO ][o.e.p.PluginsService     ] [SZjO892] loaded module [lang-expression]
[2017-05-10T15:59:29,164][INFO ][o.e.p.PluginsService     ] [SZjO892] loaded module [lang-groovy]
[2017-05-10T15:59:29,165][INFO ][o.e.p.PluginsService     ] [SZjO892] loaded module [lang-mustache]
[2017-05-10T15:59:29,165][INFO ][o.e.p.PluginsService     ] [SZjO892] loaded module [lang-painless]
[2017-05-10T15:59:29,165][INFO ][o.e.p.PluginsService     ] [SZjO892] loaded module [percolator]
[2017-05-10T15:59:29,165][INFO ][o.e.p.PluginsService     ] [SZjO892] loaded module [reindex]
[2017-05-10T15:59:29,165][INFO ][o.e.p.PluginsService     ] [SZjO892] loaded module [transport-netty3]
[2017-05-10T15:59:29,165][INFO ][o.e.p.PluginsService     ] [SZjO892] loaded module [transport-netty4]
[2017-05-10T15:59:29,166][INFO ][o.e.p.PluginsService     ] [SZjO892] no plugins loaded
127.0.0.1 - - [10/May/2017 15:59:31] "GET / HTTP/1.1" 200 -
[2017-05-10T15:59:31,813][INFO ][o.e.n.Node               ] initialized
[2017-05-10T15:59:31,813][INFO ][o.e.n.Node               ] [SZjO892] starting ...
127.0.0.1 - - [10/May/2017 15:59:34] "GET / HTTP/1.1" 200 -
[2017-05-10T15:59:37,023][INFO ][o.e.t.TransportService   ] [SZjO892] publish_address {127.0.0.1:9300}, bound_addresses {[fe80::1]:9300}, {[::1]:9300}, {127.0.0.1:9300}
[2017-05-10T15:59:37,030][WARN ][o.e.b.BootstrapChecks    ] [SZjO892] initial heap size [209715200] not equal to maximum heap size [524288000]; this can cause resize pauses and prevents mlockall from locking the entire heap
127.0.0.1 - - [10/May/2017 15:59:37] "GET / HTTP/1.1" 200 -
[2017-05-10T15:59:40,088][INFO ][o.e.c.s.ClusterService   ] [SZjO892] new_master {SZjO892}{SZjO8922TK-StMJpIV_jqg}{LkVF2ks5RLSiCqqg7_H-Nw}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2017-05-10T15:59:40,122][INFO ][o.e.g.GatewayService     ] [SZjO892] recovered [0] indices into cluster_state
[2017-05-10T15:59:40,125][INFO ][o.e.h.n.Netty4HttpServerTransport] [SZjO892] publish_address {127.0.0.1:4587}, bound_addresses {[fe80::1]:4587}, {[::1]:4587}, {127.0.0.1:4587}
[2017-05-10T15:59:40,128][INFO ][o.e.n.Node               ] [SZjO892] started
Ready.
127.0.0.1 - - [10/May/2017 15:59:40] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [10/May/2017 15:59:43] "POST / HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
File "/private/tmp/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 209, in run_wsgi
execute(self.server.app)
File "/private/tmp/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 197, in execute
application_iter = app(environ, start_response)
File "/private/tmp/localstack/.venv/lib/python2.7/site-packages/moto/server.py", line 84, in __call__
return backend_app(environ, start_response)
File "/private/tmp/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "/private/tmp/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/private/tmp/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/private/tmp/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/private/tmp/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/private/tmp/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/private/tmp/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/private/tmp/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/private/tmp/localstack/.venv/lib/python2.7/site-packages/moto/core/utils.py", line 131, in __call__
result = self.callback(request, request.url, {})
File "/private/tmp/localstack/.venv/lib/python2.7/site-packages/moto/core/responses.py", line 109, in dispatch
return cls()._dispatch(*args, **kwargs)
File "/private/tmp/localstack/.venv/lib/python2.7/site-packages/moto/core/responses.py", line 177, in _dispatch
return self.call_action()
File "/private/tmp/localstack/.venv/lib/python2.7/site-packages/moto/core/responses.py", line 194, in call_action
response = method()
File "/private/tmp/localstack/.venv/lib/python2.7/site-packages/moto/cloudformation/responses.py", line 85, in describe_stack_resource
for stack_resource in stack.stack_resources:
AttributeError: 'NoneType' object has no attribute 'stack_resources'
```

The endpoint `http://localhost:4581` is returning following response:

```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

You can reproduce this error using aws-cli:

```
aws cloudformation describe-stack-resource --stack-name test-dev --logical-resource-id ServerlessDeploymentBucket --endpoint http://localhost:4581
```

Expected result is:

```
An error occurred (ValidationError) when calling the DescribeStackResource operation: Stack 'test-dev' does not exist
```

Could you please look into this bug? Thanks!

**Comment by whummer** [comment] 2017-05-11 09:41
So, it looks like you are trying to run a `describe-stack-resource` command on a CloudFormation stack that does not exist.

If you create an empty stack first ...
```
aws cloudformation create-stack --stack-name test-dev --template-body='{"Resources":{}}' --endpoint http://localhost:4581
{
    "StackId": "arn:aws:cloudformation:us-east-1:123456789:stack/test-dev/b660f2b1-26b1-42d5-b6e7-a3859940bd93"
}
```
... then you get an error message that is a bit clearer:
```
aws cloudformation describe-stack-resource --stack-name test-dev --logical-resource-id ServerlessDeploymentBucket --endpoint http://localhost:4581

An error occurred (ValidationError) when calling the DescribeStackResource operation: Stack with id ServerlessDeploymentBucket does not exist
```

That said, the 500 error message is misleading, in fact the command should return a 4xx error. We should raise a bug request in the upstream dependency (https://github.com/spulec/moto) to get that fixed.

You mentioned that you are using serverless to create the stack - which command are you using exactly - can you please provide a reproducible test case, so we can investigate this further? Thanks

**Comment by whummer** [comment] 2017-05-14 10:09
@markatom any update on this issue? Can you please provide some test code and the serverless command you are using? Thanks

**Comment by markatom** [comment] 2017-05-17 08:13
@whummer I'll prepare TravisCI build for serverless deployment during this week. Is that okay?

**Comment by markatom** [comment] 2017-05-18 20:03
I've finally made the repository [markatom/localstack-serverless](https://github.com/markatom/localstack-serverless) for deployment of Lambda function and DynamoDB table into LocalStack. TravisCI failing build is available [here](https://travis-ci.org/markatom/localstack-serverless/builds/233768777). I've patched Serverless so that it's using LocalStack's endpoint on localhost (I'll create a merge request in Serverless's repository allowing change of the endpoint). I've also added debugging dump of every request and response it sends.

The first problem I've encountered is that describeStackResources action returns different responses when sent to LocalStack and AWS, you can test that by AWS cli:

```
# LocalStack
aws cloudformation describe-stack-resources --stack-name=test-dev --endpoint http://localhost:4581
{
    "StackResources": []
}

# AWS
aws cloudformation describe-stack-resources --stack-name=test-dev

An error occurred (ValidationError) when calling the DescribeStackResources operation: Stack with id test-dev does not exist
```

If I manage LocalStack to return HTTP 400 response then it fails with this request:

```
# LocalStack
$ aws cloudformation create-stack \
	--stack-name test-dev \
	--on-failure ROLLBACK \
	--capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
	--parameters \
	--template-body '{"AWSTemplateFormatVersion":"2010-09-09","Description":"The AWS CloudFormation template for this Serverless application","Resources":{"ServerlessDeploymentBucket":{"Type":"AWS::S3::Bucket"}},"Outputs":{"ServerlessDeploymentBucketName":{"Value":{"Ref":"ServerlessDeploymentBucket"}}}}' \
	--tags Key=STAGE,Value=dev \
	--endpoint http://localhost:4581
```

The output of LocalStack is following:

```
ERROR:localstack.mock.generic_proxy:Error forwarding request: 'Properties'
Traceback (most recent call last):
  File "/Users/tomas/prace/localstack-serverless/localstack/localstack/mock/generic_proxy.py", line 108, in forward
    data=data, headers=self.headers, response=response)
  File "/Users/tomas/prace/localstack-serverless/localstack/localstack/mock/proxy/cloudformation_listener.py", line 131, in update_cloudformation
    template_deployer.deploy_template(template)
  File "/Users/tomas/prace/localstack-serverless/localstack/localstack/utils/cloudformation/template_deployer.py", line 81, in deploy_template
    deploy_resource(resource)
  File "/Users/tomas/prace/localstack-serverless/localstack/localstack/utils/cloudformation/template_deployer.py", line 71, in deploy_resource
    params[param_key] = resource['Properties'].get(prop_key)
KeyError: 'Properties'
```

The corresponding response from AWS is:

```
# AWS
$ aws cloudformation create-stack \
        --stack-name test-dev \
        --on-failure ROLLBACK \
        --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
        --parameters \
        --template-body '{"AWSTemplateFormatVersion":"2010-09-09","Description":"The AWS CloudFormation template for this Serverless application","Resources":{"ServerlessDeploymentBucket":{"Type":"AWS::S3::Bucket"}},"Outputs":{"ServerlessDeploymentBucketName":{"Value":{"Ref":"ServerlessDeploymentBucket"}}}}' \
        --tags Key=STAGE,Value=dev
{
    "StackId": "arn:aws:cloudformation:us-west-1:952971986068:stack/test-dev/28c9f8b0-3bf9-11e7-ad0a-50fae8e9948e"
}
```

That's as far as I've gotten. I'm affraid that there will be more small issues like these that are avoiding deployment to LocalStack using Serverless. I believe it's possible to fine-tune LocalStack for use with Serverless because both of these tools are very powerful. This way I can deploy our stack to local or cloud environment with just a single command.

Please, feel free to ask me for any help concerning Serverless. Thank you for your time!

**Comment by arabold** [comment] 2017-05-23 21:46
My understanding of the CloudFormation support is that it will "simulate" the stack creation but not actually create any of the resources in the respective services. E.g. it will not create an actual DynamoDB table but just pretend that it would have done so. This allows testing of CloudFormation scripts but doesn't really allow you to perform an actual local deployment with Serverless. 

So even if Serverless gets patched to support custom endpoint-urls and all upstream dependencies to Localstack are fixed, this will *not* allow you to run a Serverless project locally without AWS. Please correct me if wrong.

**Comment by whummer** [comment] 2017-05-24 17:01
@arabold We are in the process of implementing the actual CloudFormation deployment logic, see here: https://github.com/atlassian/localstack/blob/master/localstack/utils/cloudformation/template_deployer.py That said, currently only a subset of the AWS resources are supported, but we're happy to receive future requests and/or pull requests.

@markatom I've pushed a change to enable deployment of your serverless example. Note that I had to update your patch to include the following in `awsProvider.js`:
```
request(service, method, params) {
    const that = this;
    const credentials = that.getCredentials();
    if (service === 'CloudFormation') {
      credentials.endpoint = 'http://localhost:4581';
    } else if (service === 'S3') {
      credentials.endpoint = 'http://localhost:4572';
    } else {
      ...
    }
    ...
```

Then when I run the deployment against the latest version of *LocalStack*, I get this output:
```
$ node_modules/serverless/bin/serverless deploy 
Serverless: Packaging service...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
..
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
..
Serverless: Stack update finished...
Service Information
service: test
stage: dev
region: us-east-1
api keys:
  None
endpoints:
  None
functions:
  test: test-dev-test
```

Please note that CloudFormation deployments are still work in progress, so if you encounter any follow-up issues, please raise another bug report. Thanks

Are you planning to contribute your patch (make the service endpoints configurable) to serverless? I think that would be a great step towards allowing local testing of serverless applications.

**Comment by temyers** [comment] 2017-05-27 07:26
I raised the following issue on Serverless to cover this functionality:
https://github.com/serverless/serverless/issues/3663

At the moment, it's not considered core functionality and has been closed.

I'm in the process of writing a Serverless Plugin to allow you to set endpoint details for all services.

It is still very much a work in progress and not fully working, but available here: 
https://github.com/temyers/serverless-localstack

**Comment by whummer** [comment] 2017-06-01 18:00
Awesome, thanks @temyers . I'm closing this issue for now, please re-open if you come across any other bugs using serverless deployment.

**Closed by whummer** 2017-06-01 18:00 UTC
Labels: bug
