### ISSUE TITLE
Elasticsearch fails

### ISSUE THREAD

**Issue by bstent** [atlassian/localstack#82] opened 2017-05-01 14:05 UTC
Is there something special about elasticsearch?  I cannot get this service operational.
If I set SERVICES env to not include es other services come up.

[bob@bs-localstack ~]$ localstack infra
Starting local dev environment. CTRL-C to quit.
Starting local Elasticsearch (port 4571)...
Starting mock ES service (port 4578)...
Starting mock S3 (port 4572)...
Starting mock SNS (port 4575)...
Starting mock SQS (port 4576)...
Starting mock API Gateway (port 4567)...
Starting mock DynamoDB (port 4569)...
Starting mock DynamoDB Streams service (port 4570)...
Starting mock Firehose service (port 4573)...
Starting mock Lambda service (port 4574)...
Starting mock Kinesis (port 4568)...
Starting mock Redshift (port 4577)...
Starting mock Route53 (port 4580)...
Starting mock SES (port 4579)...
Starting mock CloudFormation (port 4581)...
Elasticsearch health check failed: ConnectionError(('Connection aborted.', BadStatusLine("''",))) caused by: ConnectionError(('Connection aborted.', BadStatusLine("''",))) Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/localstack/mock/infra.py", line 270, in check_infra_elasticsearch
    out = es.cat.aliases()
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/cat.py", line 23, in aliases
    'aliases', name), params=params)
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 86, in perform_request
    raise ConnectionError('N/A', str(e), e)
ConnectionError: ConnectionError(('Connection aborted.', BadStatusLine("''",))) caused by: ConnectionError(('Connection aborted.', BadStatusLine("''",)))

ERROR checking state of local environment (after some retries): Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/localstack/mock/infra.py", line 294, in check_infra
    check_infra_elasticsearch(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/usr/lib/python2.7/site-packages/localstack/mock/infra.py", line 277, in check_infra_elasticsearch
    assert isinstance(out, basestring)
AssertionError

Traceback (most recent call last):
  File "/usr/bin/localstack", line 31, in <module>
    infra.start_infra()
  File "/usr/lib/python2.7/site-packages/localstack/mock/infra.py", line 378, in start_infra
    check_infra(apis=apis)
  File "/usr/lib/python2.7/site-packages/localstack/mock/infra.py", line 302, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/lib/python2.7/site-packages/localstack/mock/infra.py", line 302, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/lib/python2.7/site-packages/localstack/mock/infra.py", line 302, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/lib/python2.7/site-packages/localstack/mock/infra.py", line 302, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/lib/python2.7/site-packages/localstack/mock/infra.py", line 302, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/lib/python2.7/site-packages/localstack/mock/infra.py", line 302, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/lib/python2.7/site-packages/localstack/mock/infra.py", line 302, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/lib/python2.7/site-packages/localstack/mock/infra.py", line 300, in check_infra
    raise e
AssertionError
[bob@bs-localstack ~]$

**Comment by whummer** [comment] 2017-05-01 23:49
Thanks for reporting this. Can you please try installing the latest version `0.4.0` (has just been released to pypi):
```
pip uninstall localstack
pip install localstack
```
This version automatically has debug output for Elasticsearch enabled and should give you some more detailed error logs when you run `localstack infra`.

Also, this seems like a duplicate of https://github.com/atlassian/localstack/issues/75 , would be good if you could join the conversation there. Thanks

**Comment by bstent** [comment] 2017-05-02 13:36
pip install localstack was failing.  I converted to using docker container.  Thanks whummer.

**Comment by whummer** [comment] 2017-05-05 11:42
Closing this issue for now, as it seems to be fixed in the recent versions. Please re-open if the problem persists. Thanks

**Closed by whummer** 2017-05-05 11:42 UTC
Labels: installation
