### ISSUE TITLE
Can't use java aws library to put object (etag header incorrect)

### ISSUE THREAD

**Issue by westd** [atlassian/localstack#68] opened 2017-04-16 18:09 UTC
Trying to run the aws getting started sample (S3Sample.java)

putObject in the S3 client is failing with an NPE on the etag.  Debugging the code the problem is your server returns the ETag header with lower case T, 'Etag', instead of what the aws client library is expecting, 'ETag'

**Comment by whummer** [comment] 2017-04-18 08:55
Thanks for reporting this. Any chance you could create a small/minimal test case to make this easier to reproduce? The main repository for LocalStack is on Bitbucket: https://bitbucket.org/atlassian/localstack If you could fork that repo and create a test case in a separate branch, we can take a look at it in more detail. A good place to put your test class would be the existing Java/Maven project in `ext/java`. Thanks

**Comment by whummer** [comment] 2017-04-30 12:46
The `S3Sample` test class (https://github.com/aws/aws-sdk-java/blob/master/src/samples/AmazonS3/S3Sample.java) has now been added to the code base, with some minor modifications to make it run in *LocalStack*.

I was unable to reproduce the ETag header issue, though. @westd can you please pull the latest version of the code, and give it a try to see if the ETag issue still persists? Thanks

**Comment by whummer** [comment] 2017-05-14 10:17
@westd  My suspicion is that this could be a duplicate of #98 . This has been fixed in the commit ce2d37e227c1791f3c8d5dd7ccd26becba379f82, can you please give it a try with the latest version of the code (and/or latest Docker image). Thanks

**Comment by whummer** [comment] 2017-05-24 20:18
Closing this as potential duplicate which has been fixed in the meantime. Please re-open if the problem persists. Thanks.

**Closed by whummer** 2017-05-24 20:18 UTC
Labels: needs-triaging
