### ISSUE TITLE
crashes every 15 seconds

### ISSUE THREAD

**Issue by mikhailt** [atlassian/localstack#80] opened 2017-04-28 19:36 UTC
ERROR checking state of local environment (after some retries): Traceback (most recent call last):
localstack_1  |   File "localstack/mock/infra.py", line 301, in check_infra
localstack_1  |     check_infra_elasticsearch(expect_shutdown=expect_shutdown, print_error=print_error)
localstack_1  |   File "localstack/mock/infra.py", line 284, in check_infra_elasticsearch
localstack_1  |     assert isinstance(out, basestring)
localstack_1  | AssertionError 

localstack_1  | Traceback (most recent call last):
localstack_1  |   File "localstack/mock/infra.py", line 409, in <module>
localstack_1  |     start_infra()
localstack_1  |   File "localstack/mock/infra.py", line 385, in start_infra
localstack_1  |     check_infra(apis=apis)
localstack_1  |   File "localstack/mock/infra.py", line 309, in check_infra
localstack_1  |     check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
localstack_1  |   File "localstack/mock/infra.py", line 309, in check_infra
localstack_1  |     check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
localstack_1  |   File "localstack/mock/infra.py", line 309, in check_infra
localstack_1  |     check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
localstack_1  |   File "localstack/mock/infra.py", line 309, in check_infra
localstack_1  |     check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
localstack_1  |   File "localstack/mock/infra.py", line 309, in check_infra
localstack_1  |     check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
localstack_1  |   File "localstack/mock/infra.py", line 309, in check_infra
localstack_1  |     check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
localstack_1  |   File "localstack/mock/infra.py", line 309, in check_infra
localstack_1  |     check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
localstack_1  |   File "localstack/mock/infra.py", line 307, in check_infra
localstack_1  |     raise e
localstack_1  | AssertionError

**Comment by whummer** [comment] 2017-04-29 14:40
Closing this issue as a duplicate of https://github.com/atlassian/localstack/issues/75 . @mikhailt  can you please take a look at this comment, pull the latest image and provide the log output there: https://github.com/atlassian/localstack/issues/75#issuecomment-298172860 Thanks!

**Closed by whummer** 2017-04-29 14:40 UTC
